name = ""
author = "minMaximilian"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43a5d24746b23801e7e1a61f66d5e6c8d4f82963af60248b01f7ecbab5fb36dd"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
