name = "Solaire"
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5407a320742ebd4384bc7182f2678a4ec64133a02cff43fc2f7a91591db5ba78"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
