name = "Solaire"
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d203762d476ccc733fcf59240782236d25d54728fb5ee834699e87841a2acf6b"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
