name = "Solaire"
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a2623a15f45b914bdcfa148cc0cb133f03bc3387d6d7a71bc2462b818e8e1f0"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
