name = ""
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b403a91c4826160e711ce8842e81f390fc61b1f5a3ea0ae11c4a8be016ef32fd"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
