name = ""
author = "minMaximilian"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc12332c885a4f6ab615afa9c12c09b572d152822b1c3103e9bc6cfb91c397c8"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
