name = ""
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "634be166c16b1e57ecdb4806e3be9a10b2f68d7976dd606f1bf4d83f7db62997"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
