name = ""
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ebf90fd02b8d5d74eb364ee7419116693a992b94ae1cb5ba8a19307e67c32b4"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
