name = ""
author = "minMaximilian"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f65292d7c5127faebfc77d1d411e8dc98b445dd351fdd1dcfccf50cf27f79c91"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
