name = ""
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5119e8ea6d4c8c414230e6e62b00c9d3dd795ed6a264dde83d12cdee8ced4de"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
