name = ""
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52020f5b8da8c9698adb058fedbd00bb32f4197d31403b829149baa89f43527e"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
