name = "Solaire"
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82b874db38ede288d1a7b705ae3a03c43c43d216567e51d78ff8577568837058"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
