name = ""
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69c6205794dc93ddd7c083d429e2a30fa7f0042f187241a390e4b6687f92b90a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
