name = ""
author = "minMaximilian"
version = "0.0.1a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cd6d442887544eb2da9808c95a784e01bb52b4dd76a5a44828823b40d45d78a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
