name = "Solaire"
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "584ad4d6117325758f3a74fbe3cb2c6d012162786c61916a8f81167b59e802c1"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
