name = ""
author = "minMaximilian"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b21d503253affe09dd91d53aa101a3a6aa323a9fa4f3613619a1c09e362f2b3"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
