name = "Solaire"
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a73988cc7997a3d89c13a077769dbc851f507087d3eb7a886135fe4b8ebb316"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
