name = "Solaire"
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d082de9c5851b3b13b8cc862c198e74db50e378c4aa09416e0259b3bcb98ec38"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
