name = ""
author = "minMaximilian"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c57a41a3c328d720e0470f7ad54e3ed0569dc587ceca251d173228f401b6c51a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
