console.info('Block Modification');

BlockEvents.modification((e) => {
  // No tags in start_up scripts
  const logs = [
    MC('oak_log'),
    MC('oak_wood'),
    MC('stripped_oak_log'),
    MC('stripped_oak_wood'),
    DB('oak_beam'),
    MC('spruce_log'),
    MC('spruce_wood'),
    MC('stripped_spruce_log'),
    MC('stripped_spruce_wood'),
    DB('spruce_beam'),
    MC('birch_log'),
    MC('birch_wood'),
    MC('stripped_birch_log'),
    MC('stripped_birch_wood'),
    DB('birch_beam'),
    MC('jungle_log'),
    MC('jungle_wood'),
    MC('stripped_jungle_log'),
    MC('stripped_jungle_wood'),
    DB('jungle_beam'),
    MC('dark_oak_log'),
    MC('dark_oak_wood'),
    MC('stripped_dark_oak_log'),
    MC('stripped_dark_oak_wood'),
    DB('dark_oak_beam'),
    MC('acacia_log'),
    MC('acacia_wood'),
    MC('stripped_acacia_log'),
    MC('stripped_acacia_wood'),
    DB('acacia_beam'),
    MC('crimson_stem'),
    MC('stripped_crimson_stem'),
    MC('crimson_hyphae'),
    MC('stripped_crimson_hyphae'),
    DB('crimson_beam'),
    MC('warped_stem'),
    MC('stripped_warped_stem'),
    MC('warped_hyphae'),
    MC('stripped_warped_hyphae'),
    DB('warped_beam'),
    H('greenheart_log'),
    H('stripped_greenheart_log'),
    H('greenheart_wood'),
    H('stripped_greenheart_wood'),
    H('skyroot_log'),
    H('stripped_skyroot_log'),
    H('skyroot_wood'),
    H('stripped_skyroot_wood'),
    H('bloodshroom_log'),
    H('stripped_bloodshroom_log'),
    H('bloodshroom_wood'),
    H('stripped_bloodshroom_wood'),
    MC('mangrove_log'),
    MC('mangrove_wood'),
    MC('stripped_mangrove_log'),
    MC('stripped_mangrove_wood'),
    MC('cherry_log'),
    MC('cherry_wood'),
    MC('stripped_cherry_log'),
    MC('stripped_cherry_wood'),
    DB('cherry_beam'),
  ];

  logs.forEach((log) => {
    e.modify(log, (block) => {
      block.setRequiresTool(true);
    });
  });
});
