name: Packwiz Export

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
        
    - name: Setup packwiz
      run: |
        go install github.com/packwiz/packwiz@latest
        export PATH=${PATH}:`go env GOPATH`/bin

    - name: Packwiz Refresh
      run: packwiz refresh
      
    - name: Export .mrpack file
      run: packwiz modrinth export
        
    - name: Upload .mrpack file to Discord
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: export.mrpack
